In [1]:
import numpy as np
import pandas as pd

In [27]:
sozluk = {
    "column_1" : [1,2,3,4,1,6,1],
    "column_2" : [5,6,7,8,8,9,10]
}

In [28]:
dataFrame = pd.DataFrame(sozluk)

In [29]:
dataFrame

   column_1  column_2
0         1         5
1         2         6
2         3         7
3         4         8
4         1         8
5         6         9
6         1        10

In [30]:
dataFrame.describe().T

          count      mean       std  min  25%  50%  75%   max
column_1    7.0  2.571429  1.902379  1.0  1.0  2.0  3.5   6.0
column_2    7.0  7.571429  1.718249  5.0  6.5  8.0  8.5  10.0

In [31]:
dataFrame.column_1.unique() #sutundaki tekrarsız degerler

array([1, 2, 3, 4, 6])

In [32]:
dataFrame.column_1.value_counts()

column_1
1    3
2    1
3    1
4    1
6    1
Name: count, dtype: int64